# config/datasets.yaml
datasets:
  - name: brats20
    type: kaggle
    ref: awsaf49/brats20-dataset-training-validation   # Kaggle "owner/dataset"
    dest: data/brats20
    archive: brats20.zip
    extract: true

  - name: brain_tumor_small
    type: kaggle
    ref: navoneel/brain-mri-images-for-brain-tumor-detection
    dest: data/brain_tumor_small
    archive: brain-mri-images-for-brain-tumor-detection.zip
    extract: true

  - name: ixi_sample
    type: gdrive
    dest: data/ixi
    archive: ixi_sample.zip
    extract: true

  - name: custom_from_url
    type: url
    url: https://example.com/some_dataset.zip
    dest: data/custom_from_url
    archive: some_dataset.zip
    extract: true
